name: bread
on:
  workflow_dispatch:
    inputs:
      service-name:
        type: string
        required: true
        default: blank service
jobs:
  do-a-thing:
    runs-on: ubuntu-latest
    env:
      SERVICE: ${{ inputs.service-name }}
    steps:
      - run:
          echo $SERVICE
