name: called workflow
on:
  workflow_run:
    workflows: [calling workflow]
    types:
      - completed
jobs:
  do-a-thing:
    runs-on: ubuntu-latest
    steps:
      run:
        echo "I did a thing"
